export const deskStructure = (S) =>
    S.list()
        .title('Unterseite')
        .items([
            S.listItem()
                .title('Home')
                .child(
                    S.list()
                        .title('Element')
                        .items([
                            S.listItem()
                                .title('Banner')
                                .child(S.document().schemaType('homeBanner').documentId('homeBanner')),
                            S.listItem()
                                .title('Mittagstisch Beschreibung')
                                .child(S.document().schemaType('homeLunchSection').documentId('homeLunchSection')),
                            S.listItem()
                                .title('Dinnerevents Beschreibung')
                                .child(S.document().schemaType('homeDinnerSection').documentId('homeDinnerSection')),
                        ]),
                ),
            S.listItem()
                .title('Über uns')
                .child(
                    S.list()
                        .title('Element')
                        .items([
                            S.listItem()
                                .title('Banner')
                                .child(S.document().schemaType('aboutBanner').documentId('aboutBanner')),
                            S.listItem()
                                .title('Über Nina')
                                .child(S.document().schemaType('aboutNina').documentId('aboutNina')),
                            S.listItem()
                                .title('Über Sophia')
                                .child(S.document().schemaType('aboutSophia').documentId('aboutSophia')),
                            S.listItem()
                                .title('Über uns Karussell')
                                .child(S.document().schemaType('aboutCarousel').documentId('aboutCarousel')),
                            S.listItem()
                                .title('Happa für Zuhause')
                                .child(S.document().schemaType('aboutHappaForHome').documentId('aboutHappaForHome')),
                        ]),
                ),
            S.listItem()
                .title('Mittag')
                .child(
                    S.list()
                        .title('Element')
                        .items([
                            S.listItem()
                                .title('Tageskarte')
                                .child(S.document().schemaType('lunchMenu').documentId('lunchMenu')),
                            S.listItem()
                                .title('Mittagstisch Beschreibung')
                                .child(S.document().schemaType('lunchDescription').documentId('lunchDescription')),
                        ]),
                ),
            S.listItem()
                .title('Dinner')
                .child(
                    S.list()
                        .title('Element')
                        .items([
                            S.listItem()
                                .title('Tageskarte')
                                .child(S.document().schemaType('lunchMenu').documentId('lunchMenu')),
                        ]),
                ),
            S.listItem()
                .title('Events')
                .child(
                    S.list()
                        .title('Element')
                        .items([
                            S.listItem()
                                .title('Tageskarte')
                                .child(S.document().schemaType('lunchMenu').documentId('lunchMenu')),
                        ]),
                ),
            S.listItem()
                .title('Gutscheine')
                .child(
                    S.list()
                        .title('Element')
                        .items([
                            S.listItem()
                                .title('Tageskarte')
                                .child(S.document().schemaType('lunchMenu').documentId('lunchMenu')),
                        ]),
                ),
            S.listItem()
                .title('Partner')
                .child(
                    S.list()
                        .title('Element')
                        .items([
                            S.listItem()
                                .title('Tageskarte')
                                .child(S.document().schemaType('lunchMenu').documentId('lunchMenu')),
                        ]),
                ),
            S.listItem()
                .title('Presse')
                .child(
                    S.list()
                        .title('Element')
                        .items([
                            S.listItem()
                                .title('Tageskarte')
                                .child(S.document().schemaType('lunchMenu').documentId('lunchMenu')),
                        ]),
                ),
            S.listItem()
                .title('Impressum')
                .child(
                    S.list()
                        .title('Element')
                        .items([
                            S.listItem()
                                .title('Tageskarte')
                                .child(S.document().schemaType('lunchMenu').documentId('lunchMenu')),
                        ]),
                ),
            S.listItem()
                .title('Datenschutz')
                .child(
                    S.list()
                        .title('Element')
                        .items([
                            S.listItem()
                                .title('Tageskarte')
                                .child(S.document().schemaType('lunchMenu').documentId('lunchMenu')),
                        ]),
                ),
        ])
