export const deskStructure = (S) =>
    S.list()
        .title('Unterseiten')
        .items([
            S.listItem()
                .title('Home')
                .child(
                    S.list()
                        .title('Elemente')
                        .items([
                            S.listItem()
                                .title('Banner')
                                .child(S.document().schemaType('homeBanner').documentId('homeBanner')),
                            S.listItem()
                                .title('Mittagstisch Beschreibung')
                                .child(S.document().schemaType('homeLunchSection').documentId('homeLunchSection')),
                            S.listItem()
                                .title('Dinnerevents Beschreibung')
                                .child(S.document().schemaType('homeDinnerSection').documentId('homeDinnerSection')),
                        ]),
                ),
            S.listItem()
                .title('Über uns')
                .child(
                    S.list()
                        .title('Elemente')
                        .items([
                            S.listItem()
                                .title('Tageskarte')
                                .child(S.document().schemaType('lunchMenu').documentId('lunchMenu')),
                        ]),
                ),
            S.listItem()
                .title('Mittag')
                .child(
                    S.list()
                        .title('Elemente')
                        .items([
                            S.listItem()
                                .title('Tageskarte')
                                .child(S.document().schemaType('lunchMenu').documentId('lunchMenu')),
                        ]),
                ),
            S.listItem()
                .title('Dinner')
                .child(
                    S.list()
                        .title('Elemente')
                        .items([
                            S.listItem()
                                .title('Tageskarte')
                                .child(S.document().schemaType('lunchMenu').documentId('lunchMenu')),
                        ]),
                ),
            S.listItem()
                .title('Events')
                .child(
                    S.list()
                        .title('Elemente')
                        .items([
                            S.listItem()
                                .title('Tageskarte')
                                .child(S.document().schemaType('lunchMenu').documentId('lunchMenu')),
                        ]),
                ),
            S.listItem()
                .title('Gutscheine')
                .child(
                    S.list()
                        .title('Elemente')
                        .items([
                            S.listItem()
                                .title('Tageskarte')
                                .child(S.document().schemaType('lunchMenu').documentId('lunchMenu')),
                        ]),
                ),
            S.listItem()
                .title('Partner')
                .child(
                    S.list()
                        .title('Elemente')
                        .items([
                            S.listItem()
                                .title('Tageskarte')
                                .child(S.document().schemaType('lunchMenu').documentId('lunchMenu')),
                        ]),
                ),
            S.listItem()
                .title('Presse')
                .child(
                    S.list()
                        .title('Elemente')
                        .items([
                            S.listItem()
                                .title('Tageskarte')
                                .child(S.document().schemaType('lunchMenu').documentId('lunchMenu')),
                        ]),
                ),
            S.listItem()
                .title('Impressum')
                .child(
                    S.list()
                        .title('Elemente')
                        .items([
                            S.listItem()
                                .title('Tageskarte')
                                .child(S.document().schemaType('lunchMenu').documentId('lunchMenu')),
                        ]),
                ),
            S.listItem()
                .title('Datenschutz')
                .child(
                    S.list()
                        .title('Elemente')
                        .items([
                            S.listItem()
                                .title('Tageskarte')
                                .child(S.document().schemaType('lunchMenu').documentId('lunchMenu')),
                        ]),
                ),
        ])
